### PR TITLE
getting-started fixes

### PR DESCRIPTION
**Pull request by lishine**

### CODE REVIEW

**Comment by lishine** [comment]
Your lib is working!
On the previous project I used Hasura.
Now I started with apollo server + postgres client.
But at the point where I need to do pagination with sorting+filtering, I started to think how to convert variables into sql queries.
And so understood that Hasura did for me this work.
And so trying to use your solution!
I know it is alpha. But this is only a first feature of the product, so I hope this lib get more mature by the time product will progress.

I want to help in anything!

**Comment by lishine** [comment]
I would suggest changing into 'import' syntax instead of require. Node 14 supports it  and typescript of course.

**Comment by lishine** [comment]
Tried to setup with graphql-codegen.
And the only way I had success (it didn't find the type declared in sqlmancer schema file) is putting all of my types into sqlmancer schema file and importing this file into
```
        schema: makeSqlmancerSchema({
            typeDefs: schema,
            resolvers: resolvers,
        }),
```
Though I didn't experiment till now with any schema merging. So something I am doing wrong. Anyway I am good as it is now.
If you hint me how to do it right, I will add an example to the documentation.

**Comment by lishine** [comment]
WOW :1st_place_medal: :rocket: :guitar: 
@where, @orderBy it just work! so cool!
offset and limit also works but explicitly, they could be also added as @offsetPagination

**Comment by danielrearden** [comment]
Thanks so much for trying out the library and for all your feedback! I'm wrapping up the remaining work for a beta release. Once I've done that, I'll come back to the docs since they still need a lot of ❤️ . Thank you for these fixes though!

The upcoming release will include a lot of [new features](https://github.com/danielrearden/sqlmancer/milestone/1) including MySQL/MariaDB/SQLite support, aggregate queries and read-only models. I've also improved the workflow a bit -- you won't have to build the client ahead of time anymore -- the only thing you'll need to generate separate are typings and those are optional.

**Comment by lishine** [comment]
Dates:
This works:
```
query {
    type Order @model(table: "orders", pk: "id") {
        id: ID!
        createdAt: String!
    }
  orders(where: {createdAt : {greaterThan: "2011-10-05T14:48:00.000Z"}} orderBy: { id: DESC} limit: 3, offset: 1) {
    id
    createdAt
  }
}
```

But returns a date in a ticks format '111234234'
So it seems to me asymetric
2. tried to use custom scalar
But it does'nt add it to the where:
```Field \"createdAt\" is not defined by type \"OrderWhere\"."```
scheme:
```
    scalar DateTime
    type Order @model(table: "orders", pk: "id") {
        id: ID!
        createdAt: DateTime!
    }
```
resolvers:
```
import { DateTimeResolver } from 'graphql-scalars'
export const resolvers: Resolvers = {
    DateTime: DateTimeResolver,
```

**Comment by danielrearden** [comment]
Re: Dates

I've added custom scalar support but will need to cut a release. The config is moving to a single directive on the query type and will include a `customScalars` argument:

```
type Query
    @sqlmancer(
      dialect: POSTGRES,
      transformFieldNames: SNAKE_CASE,
      customScalars: { JSON: ["JSON", "JSONObject"]
}) {
  # fields here
}
```

I'm writing up integration tests now. I'll make a note to add a DateTime scalar and make sure it's working as expected. We'll need to add a guide for custom scalars anyway, so we can include examples of commonly used ones like dates and JSON.

**Pull request merged**
